org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8

springBootVersion=3.4.1
springDependencyManagementVersion=1.1.7
lombokVersion=1.18.34
mapstructVersion=1.6.3
jooqVersion=3.19.18
liquibaseVersion=4.30.0
postgresVersion=42.7.4
resilience4jVersion=2.3.0
testcontainersVersion=1.21.0
archunitVersion=1.3.0
dddBuildingBlocksVersion=1.0.0
usecasePatternVersion=1.1.0
usecasePatternStarterVersion=1.1.0
hexagonalArchitectureVersion=1.0.0
