spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/catalog
    username: catalog
    password: catalog
  jpa:
    open-in-view: false
  liquibase:
    contexts: production
  kafka:
    listener:
      auto-startup: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

logging:
  level:
    org.jooq: WARN
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE

storage:
  images:
    bucket: marketplace-images
    endpoint: http://localhost:9000
    region: us-east-1
    access-key: test-access
    secret-key: test-secret
    upload-ttl-minutes: 10
    download-ttl-minutes: 60
