server:
  port: 8082

spring:
  application:
    name: catalog-starter
  datasource:
    url: jdbc:postgresql://localhost:5439/catalog_starter
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: redis
    redis:
      time-to-live: 10m
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
